import type { VisualizationConfig } from "./visualisation-store"
export const sampleData: VisualizationConfig = {
  canvasStyle: {
    width: 1200,
    height: 800,
    backgroundColor: "#1a1a2e",
  },
  rootLayerId: "water-cycle",
  layers: {
    "water-cycle": {
      id: "water-cycle",
      name: "Water Cycle",
      backgroundColor: "#0f3460",
      parentNodeId: undefined,
      nodes: [
        {
          id: "evaporation",
          name: "Evaporation",
          x: 300,
          y: 200,
          radius: 60,
          color: "#e94560",
          childLayerId: "evaporation-details",
        },
        {
          id: "condensation",
          name: "Condensation",
          x: 600,
          y: 200,
          radius: 60,
          color: "#16c784",
          childLayerId: "condensation-details",
        },
        {
          id: "precipitation",
          name: "Precipitation",
          x: 900,
          y: 200,
          radius: 60,
          color: "#0084ff",
          childLayerId: "precipitation-details",
        },
      ],
    },
    "evaporation-details": {
      id: "evaporation-details",
      name: "Evaporation Details",
      backgroundColor: "#e94560",
      parentNodeId: "evaporation",
      nodes: [
        {
          id: "solar-heat",
          name: "Solar Heat",
          x: 300,
          y: 200,
          radius: 50,
          color: "#ffa500",
        },
        {
          id: "water-surface",
          name: "Water Surface",
          x: 600,
          y: 200,
          radius: 50,
          color: "#00bfff",
        },
        {
          id: "vapor-formation",
          name: "Vapor Formation",
          x: 900,
          y: 200,
          radius: 50,
          color: "#87ceeb",
        },
      ],
    },
    "condensation-details": {
      id: "condensation-details",
      name: "Condensation Details",
      backgroundColor: "#16c784",
      parentNodeId: "condensation",
      nodes: [
        {
          id: "cooling",
          name: "Cooling",
          x: 300,
          y: 200,
          radius: 50,
          color: "#4169e1",
        },
        {
          id: "nucleation",
          name: "Nucleation",
          x: 600,
          y: 200,
          radius: 50,
          color: "#6495ed",
        },
        {
          id: "cloud-formation",
          name: "Cloud Formation",
          x: 900,
          y: 200,
          radius: 50,
          color: "#add8e6",
        },
      ],
    },
    "precipitation-details": {
      id: "precipitation-details",
      name: "Precipitation Details",
      backgroundColor: "#0084ff",
      parentNodeId: "precipitation",
      nodes: [
        {
          id: "rain",
          name: "Rain",
          x: 300,
          y: 200,
          radius: 50,
          color: "#1e90ff",
        },
        {
          id: "snow",
          name: "Snow",
          x: 600,
          y: 200,
          radius: 50,
          color: "#f0f8ff",
        },
        {
          id: "collection",
          name: "Collection",
          x: 900,
          y: 200,
          radius: 50,
          color: "#00008b",
        },
      ],
    },
  },
}
